# Generated by Django 6.0.2 on 2026-02-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('number', models.IntegerField(verbose_name='Nro. de Cabaña')),
                ('descrition', models.TextField(verbose_name='Descripcion')),
                ('rooms', models.IntegerField(verbose_name='Nro. de Habitaciones')),
                ('bathrooms', models.IntegerField(verbose_name='Baños')),
                ('dining', models.IntegerField(verbose_name='Comedor')),
                ('kitchen', models.IntegerField(verbose_name='Cocina')),
                ('availability', models.BooleanField(blank=True, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('show_home', models.BooleanField(default=False, verbose_name='Mostrar en el Inicio')),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
            },
        ),
    ]
