# Generated by Django 6.0.2 on 2026-02-21 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabin', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.IntegerField()),
                ('entrance', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Entrada')),
                ('exit', models.DateTimeField(verbose_name='Fecha y Hora de Salida')),
                ('cabin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabin.cabin')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
